import { useLanguage } from "../Language";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FiArrowRight, FiSearch, FiShield, FiUsers, FiMapPin, FiHeart } from "react-icons/fi";
import "./Home.css";

export default function Home() {
  const { t } = useLanguage();
  const navigate = useNavigate();
  const [gender, setGender] = useState("Female");
  const [minAge, setMinAge] = useState("22");
  const [maxAge, setMaxAge] = useState("30");
  const [religion, setReligion] = useState("");
  const [motherTongue, setMotherTongue] = useState("Tamil");
  const [error, setError] = useState("");
  const ages = Array.from({ length: 43 }, (_, i) => i + 18);
  function search(event) {
    event.preventDefault();
    if (+minAge > +maxAge) { setError("Minimum age must be lower than or equal to maximum age."); return; }
    navigate("/profiles", { state: { gender, minAge, maxAge, religion, motherTongue } });
  }
  return <main className="home-page"><section className="hero-section"><img className="hero-photo" src="/tamil-wedding-hero.png" alt={t("Tamil bride and groom wearing traditional wedding attire and flower garlands")} fetchPriority="high" /><div className="hero-shade" /><div className="home-container hero-content"><p className="hero-kicker">{t("ROOTED IN FAMILY. OPEN TO POSSIBILITY.")}</p><h1>{t("Namakkal")}<br />{t("Matrimony")}</h1><p className="hero-copy">{t("A meaningful connection.")}<br />{t("A new chapter, together.")}</p><p className="hero-description">{t("Meet people who share your values, from Namakkal and across Tamil Nadu.")}</p><Link to={localStorage.getItem("token") ? "/profiles" : "/register"} className="home-primary">{localStorage.getItem("token") ? t("Find your match") : t("Create your profile")}<FiArrowRight /></Link></div><span className="hero-caption">{t("For the journey that matters.")}</span></section>
    <section className="search-band"><div className="home-container"><div className="search-heading"><FiSearch /><h2>{t("Find someone who feels right for you")}</h2></div><form className="match-form" onSubmit={search}><label>{t("Looking for")}<select value={gender} onChange={e => setGender(e.target.value)}><option value="Female">{t("A bride")}</option><option value="Male">{t("A groom")}</option></select></label><fieldset className="age-field"><legend>{t("Age range")}</legend><div><select aria-label={t("Minimum age")} value={minAge} onChange={e => { setMinAge(e.target.value); setError(""); }}>{ages.map(age => <option key={age}>{age}</option>)}</select><span>{t("to")}</span><select aria-label={t("Maximum age")} value={maxAge} onChange={e => { setMaxAge(e.target.value); setError(""); }}>{ages.map(age => <option key={age}>{age}</option>)}</select></div></fieldset><label>{t("Religion")}<select value={religion} onChange={e => setReligion(e.target.value)}><option value="">{t("Any religion")}</option>{["Hindu", "Muslim", "Christian", "Jain", "Other"].map(v => <option key={v} value={v}>{t(v)}</option>)}</select></label><label>{t("Mother tongue")}<select value={motherTongue} onChange={e => setMotherTongue(e.target.value)}><option value="">{t("Any language")}</option>{["Tamil", "Malayalam", "Telugu", "Kannada", "Hindi", "English"].map(v => <option key={v} value={v}>{t(v)}</option>)}</select></label><button className="home-primary" type="submit"><FiSearch />{t("Search profiles")}</button></form>{error && <p className="form-error" role="alert">{error}</p>}</div></section>
    <section className="home-container confidence-section"><div className="home-section-heading"><div><p className="section-kicker">{t("A PERSONAL APPROACH")}</p><h2>{t("Shared values.")}<br />{t("Lasting possibilities.")}</h2></div><p>{t("Finding a life partner is personal. Make space for the details, the conversations, and the family connections that matter to you.")}</p></div><div className="confidence-grid">{[[FiMapPin, "Closer to your roots", "Discover profiles by district, native place, language, and education."], [FiShield, "Privacy in your hands", "Choose how your photos and contact details are shared."], [FiUsers, "Family comes naturally", "Create a profile for yourself or someone in your family."]].map(([Icon, title, description]) => <article key={title}><Icon /><h3>{t(title)}</h3><p>{t(description)}</p></article>)}</div></section>
    <section className="process-section"><div className="home-container"><p className="section-kicker">{t("YOUR NEXT CHAPTER")}</p><h2>{t("A connection begins")}<br />{t("with a simple hello.")}</h2><ol className="process-list"><li><span>01</span><h3>{t("Tell your story")}</h3><p>{t("Add your personal details, family background, and partner preferences.")}</p></li><li><span>02</span><h3>{t("Explore your possibilities")}</h3><p>{t("Discover profiles and save the people you would like to get to know.")}</p></li><li><span>03</span><h3>{t("Make a connection")}</h3><p>{t("Send an interest and begin a conversation once it is accepted.")}</p></li></ol></div></section>
    <section className="home-container final-cta"><FiHeart /><p className="section-kicker">{t("BEGIN AT YOUR OWN PACE")}</p><h2>{t("Your story deserves")}<br />{t("a beautiful next chapter.")}</h2><Link className="home-primary" to={localStorage.getItem("token") ? "/profiles" : "/register"}>{localStorage.getItem("token") ? t("Explore profiles") : t("Join Namakkal Matrimony")}<FiArrowRight /></Link></section></main>;
}
