import { createContext, useContext, useEffect, useState } from "react";
import customerTamil from "./customerTamil";

const Context = createContext({ language: "en", setLanguage: () => {}, t: text => text });
const tamil = {
  "No photo": "புகைப்படம் இல்லை", "years": "வயது",
  "Change password": "கடவுச்சொல்லை மாற்று", "New password": "புதிய கடவுச்சொல்", "Confirm password": "கடவுச்சொல்லை உறுதிப்படுத்து", "Passwords do not match": "கடவுச்சொற்கள் பொருந்தவில்லை", "Password must be 8 characters or more and at most 72 UTF-8 bytes": "கடவுச்சொல் குறைந்தது 8 எழுத்துகள் மற்றும் அதிகபட்சம் 72 UTF-8 பைட்டுகள் இருக்க வேண்டும்",
  "Search name, email, district or age": "பெயர், மின்னஞ்சல், மாவட்டம் அல்லது வயது",
  "Job": "வேலை", "Both": "இரண்டும்", "Job type": "வேலை வகை", "Job category": "வேலைப் பிரிவு", "Job location": "வேலை இருப்பிடம்", "Experience (years)": "அனுபவம் (ஆண்டுகள்)", "Full-time": "முழுநேரம்", "Part-time": "பகுதிநேரம்", "Contract": "ஒப்பந்தம்", "Freelance": "சுயாதீன வேலை", "Internship": "பயிற்சி வேலை",
  "Select": "தேர்ந்தெடு", "Register as": "பதிவு செய்பவர்", "Self": "சுயம்", "Parent": "பெற்றோர்", "Sibling": "சகோதரர் / சகோதரி", "Relative": "உறவினர்", "Friend": "நண்பர்", "Never Married": "திருமணமாகாதவர்", "Divorced": "விவாகரத்தானவர்", "Widowed": "துணையை இழந்தவர்",
  "Career and business": "தொழில் மற்றும் வணிகம்", "NRI": "வெளிநாடு வாழ் இந்தியர்", "Yes": "ஆம்", "No": "இல்லை", "Private Job": "தனியார் வேலை", "Government Job": "அரசு வேலை", "Business": "வணிகம்", "Self Employed": "சுயதொழில்", "Professional": "தொழில்முறை பணியாளர்", "Farmer": "விவசாயி", "Student": "மாணவர்", "Business type": "வணிக வகை", "Manufacturing": "உற்பத்தி", "Wholesale": "மொத்த விற்பனை", "Retail": "சில்லறை விற்பனை", "IT": "தகவல் தொழில்நுட்பம்", "Construction": "கட்டுமானம்", "Finance": "நிதி", "Healthcare": "சுகாதாரம்", "Business category": "வணிகப் பிரிவு", "Business location": "வணிக இருப்பிடம்", "Business website": "வணிக இணையதளம்", "Years in business": "வணிக அனுபவ ஆண்டுகள்", "Number of employees": "பணியாளர் எண்ணிக்கை", "Number of branches": "கிளைகளின் எண்ணிக்கை", "Branch locations": "கிளை இருப்பிடங்கள்", "Social media": "சமூக வலைதளம்",
  "Family details": "குடும்ப விவரங்கள்", "Father occupation": "தந்தை தொழில்", "Mother occupation": "தாய் தொழில்", "Brothers": "சகோதரர்கள்", "Married brothers": "திருமணமான சகோதரர்கள்", "Sisters": "சகோதரிகள்", "Married sisters": "திருமணமான சகோதரிகள்", "Family type": "குடும்ப வகை", "Joint": "கூட்டுக் குடும்பம்", "Nuclear": "தனிக் குடும்பம்", "Family status": "குடும்ப நிலை", "Middle Class": "நடுத்தர வர்க்கம்", "Upper Middle Class": "உயர் நடுத்தர வர்க்கம்", "Rich": "செல்வந்தர்",
  "Religion and community": "மதம் மற்றும் சமூகம்", "Kuladeivam": "குலதெய்வம்", "Horoscope details": "ஜாதக விவரங்கள்", "Lagnam": "லக்னம்", "Gothram": "கோத்திரம்", "Dosha": "தோஷம்", "Birth time": "பிறந்த நேரம்", "Birth place": "பிறந்த இடம்", "Horoscope available": "ஜாதகம் உள்ளது", "Sevvai dosham": "செவ்வாய் தோஷம்", "Rahu Kethu dosham": "ராகு கேது தோஷம்",
  "Partner preferences": "துணை விருப்பங்கள்", "Preferred age from": "விருப்ப வயது முதல்", "Preferred age to": "விருப்ப வயது வரை", "Preferred height": "விரும்பும் உயரம்", "Preferred education": "விரும்பும் கல்வி", "Preferred occupation": "விரும்பும் தொழில்", "Preferred religion": "விரும்பும் மதம்", "Preferred caste": "விரும்பும் சாதி", "Preferred location": "விரும்பும் இருப்பிடம்", "Preferred star": "விரும்பும் நட்சத்திரம்", "Preferred rashi": "விரும்பும் ராசி", "Accept Sevvai dosham": "செவ்வாய் தோஷம் ஏற்கலாம்", "Horoscope matching required": "ஜாதகப் பொருத்தம் தேவை",
  "Assets": "சொத்துகள்", "Land acres": "நிலம் ஏக்கர்", "Land value": "நில மதிப்பு", "House": "வீடு", "Vehicle": "வாகனம்", "Other assets": "பிற சொத்துகள்", "Privacy and membership": "தனியுரிமை மற்றும் உறுப்பினர் வகை", "Profile visibility": "விவரக் காட்சிநிலை", "Public": "பொது", "Members Only": "உறுப்பினர்களுக்கு மட்டும்", "Private": "தனிப்பட்டது", "Hide mobile": "கைபேசியை மறை", "Hide income": "வருமானத்தை மறை", "Hide company": "நிறுவனத்தை மறை", "Hide photos": "புகைப்படங்களை மறை", "GST verified": "GST சரிபார்க்கப்பட்டது", "Business verified": "வணிகம் சரிபார்க்கப்பட்டது", "Photos and documents": "புகைப்படங்கள் மற்றும் ஆவணங்கள்", "Main photo": "முதன்மைப் புகைப்படம்", "Profile photos": "சுயவிவரப் புகைப்படங்கள்", "Family photos": "குடும்பப் புகைப்படங்கள்", "Office photos": "அலுவலகப் புகைப்படங்கள்", "Horoscope file": "ஜாதகக் கோப்பு", "Each file must be 10 MB or smaller, with at most 10 photos per category.": "ஒவ்வொரு கோப்பும் 10 MB-க்குள் இருக்க வேண்டும். ஒரு பிரிவில் அதிகபட்சம் 10 புகைப்படங்கள்.", "Invalid preferred age range": "விருப்ப வயது வரம்பு தவறானது", "Invalid married sibling count": "திருமணமான சகோதரர்கள் எண்ணிக்கை தவறானது", "Invalid count: enter a non-negative whole number": "எண்ணிக்கையில் பூஜ்யம் அல்லது நேர்மறை முழு எண்ணை உள்ளிடவும்",
  "NAMAKKAL MATRIMONY": "நாமக்கல் மேட்ரிமோனி",
  "Meaningful connections.": "அர்த்தமுள்ள உறவுகள்.", "Thoughtfully managed.": "அக்கறையுடன் நிர்வகிக்கப்படுகிறது.", "Namakkal Matrimony": "நாமக்கல் மேட்ரிமோனி",
  "Overview": "கண்ணோட்டம்", "Members": "உறுப்பினர்கள்", "Premium": "பிரீமியம்", "Reports": "அறிக்கைகள்", "Settings": "அமைப்புகள்", "Administration": "நிர்வாகம்", "ADMINISTRATION": "நிர்வாகம்", "WORKSPACE": "பணியிடம்", "COMMUNITY": "சமூகம்", "INSIGHTS": "புள்ளிவிவரங்கள்", "Administrator": "நிர்வாகி", "Administration workspace": "நிர்வாகப் பணியிடம்", "Sign out": "வெளியேறு", "Go back": "பின்செல்", "Main navigation": "முதன்மை வழிசெலுத்தல்", "Toggle navigation": "வழிசெலுத்தலை மாற்று", "Close navigation": "வழிசெலுத்தலை மூடு",
  "Add member": "உறுப்பினரைச் சேர்", "Edit member": "உறுப்பினரைத் திருத்து", "Delete member": "உறுப்பினரை நீக்கு", "Save member": "உறுப்பினரைச் சேமி", "Saving...": "சேமிக்கப்படுகிறது...", "Deleting...": "நீக்கப்படுகிறது...", "Cancel": "ரத்து", "Close": "மூடு", "Edit": "திருத்து", "Delete": "நீக்கு", "View": "பார்", "Actions": "செயல்கள்", "Member profile": "உறுப்பினர் விவரம்", "Close profile": "விவரத்தை மூடு", "Not provided": "வழங்கப்படவில்லை", "Member": "உறுப்பினர்", "Age / Gender": "வயது / பாலினம்", "District": "மாவட்டம்", "Religion": "மதம்", "Membership": "உறுப்பினர் வகை", "Profile": "விவரம்", "Standard": "சாதாரணம்", "Unnamed member": "பெயரில்லா உறுப்பினர்", "No email provided": "மின்னஞ்சல் இல்லை", "Not specified": "குறிப்பிடப்படவில்லை", "Loading profiles...": "விவரங்கள் ஏற்றப்படுகின்றன...", "Member records are unavailable.": "உறுப்பினர் விவரங்கள் கிடைக்கவில்லை.", "No members found.": "உறுப்பினர்கள் இல்லை.", "Email": "மின்னஞ்சல்", "Phone": "தொலைபேசி", "Age": "வயது", "Gender": "பாலினம்", "Name": "பெயர்", "Password": "கடவுச்சொல்", "Mobile": "கைபேசி", "Date of birth": "பிறந்த தேதி", "Height": "உயரம்", "Weight": "எடை", "Native place": "சொந்த ஊர்", "Current city": "தற்போதைய நகரம்", "State": "மாநிலம்", "Country": "நாடு", "Marital status": "திருமண நிலை", "Education": "கல்வி", "Occupation": "தொழில்", "Company": "நிறுவனம்", "Annual income": "ஆண்டு வருமானம்", "Caste": "சாதி", "Subcaste": "உட்பிரிவு", "Mother tongue": "தாய்மொழி", "Star": "நட்சத்திரம்", "Rashi": "ராசி", "Father name": "தந்தை பெயர்", "Mother name": "தாய் பெயர்", "Address": "முகவரி", "Expectations": "எதிர்பார்ப்புகள்", "Select gender": "பாலினத்தைத் தேர்ந்தெடு", "Male": "ஆண்", "Female": "பெண்", "Other": "மற்றவை", "Premium membership": "பிரீமியம் உறுப்பினர்", "Basic information": "அடிப்படை விவரங்கள்", "Location and contact": "இருப்பிடம் மற்றும் தொடர்பு", "Personal details": "தனிப்பட்ட விவரங்கள்", "Career and family": "தொழில் மற்றும் குடும்பம்", "Member added.": "உறுப்பினர் சேர்க்கப்பட்டார்.", "Member updated.": "உறுப்பினர் திருத்தப்பட்டார்.", "Member deleted.": "உறுப்பினர் நீக்கப்பட்டார்.", "This permanently deletes the member account and its messages.": "இது உறுப்பினர் கணக்கையும் அதன் செய்திகளையும் நிரந்தரமாக நீக்கும்.", "Unable to save member. Please try again.": "உறுப்பினரைச் சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.", "Unable to delete member. Please try again.": "உறுப்பினரை நீக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.", "This email address is already registered": "இந்த மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது", "Your session has expired. Please sign in again.": "அமர்வு காலாவதியானது. மீண்டும் உள்நுழையவும்.", "Administrator access is required": "நிர்வாகி அனுமதி தேவை", "Password must contain at least 8 characters": "கடவுச்சொல்லில் குறைந்தது 8 எழுத்துகள் தேவை", "Age must be between 18 and 100": "வயது 18 முதல் 100 வரை இருக்க வேண்டும்", "Name and a valid email address are required": "பெயரும் செல்லுபடியாகும் மின்னஞ்சலும் தேவை",
  "Premium members": "பிரீமியம் உறுப்பினர்கள்", "Your premium member directory.": "பிரீமியம் உறுப்பினர் பட்டியல்.", "Browse and review member profiles.": "உறுப்பினர் விவரங்களைப் பார்வையிடவும்.", "Export CSV": "CSV ஏற்றுமதி", "Search members": "உறுப்பினரைத் தேடு", "Search name, email or district": "பெயர், மின்னஞ்சல் அல்லது மாவட்டம்", "Filter by gender": "பாலின வடிகட்டி", "All genders": "அனைத்து பாலினங்கள்", "Filter by membership": "உறுப்பினர் வகை வடிகட்டி", "All memberships": "அனைத்து வகைகள்", "Refresh members": "பட்டியலைப் புதுப்பி", "Previous page": "முந்தைய பக்கம்", "Next page": "அடுத்த பக்கம்", "of": "மொத்தம்", "members": "உறுப்பினர்கள்", "Loading member records...": "உறுப்பினர் விவரங்கள் ஏற்றப்படுகின்றன...", "Try again": "மீண்டும் முயற்சி", "Unable to load members. Check your connection and try again.": "உறுப்பினர்களை ஏற்ற முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.", "Your session cannot access members. Sign out and sign in again.": "உறுப்பினர்களை அணுக முடியவில்லை. வெளியேறி மீண்டும் உள்நுழையவும்.",
  "Your community, at a glance.": "உங்கள் சமூகத்தின் சுருக்கம்.", "View members": "உறுப்பினர்களைப் பார்", "Total members": "மொத்த உறுப்பினர்கள்", "Standard members": "சாதாரண உறுப்பினர்கள்", "Districts represented": "மாவட்டங்கள்", "Current member records": "தற்போதைய உறுப்பினர் பதிவுகள்", "Membership mix": "உறுப்பினர் வகைகள்", "Total profiles": "மொத்த விவரங்கள்", "Community breakdown": "சமூகப் பிரிவுகள்", "Other / unspecified": "மற்றவை / குறிப்பிடப்படவில்லை", "Member directory": "உறுப்பினர் பட்டியல்", "A snapshot of your community": "உங்கள் சமூகத்தின் சுருக்கம்", "View all": "அனைத்தையும் பார்", "Membership distribution across your community.": "சமூகத்தில் உறுப்பினர் பகிர்வு.", "Export members": "உறுப்பினர் ஏற்றுமதி", "Members by district": "மாவட்ட வாரியான உறுப்பினர்கள்", "districts": "மாவட்டங்கள்", "Share of community": "சமூகத்தின் பங்கு", "Loading report...": "அறிக்கை ஏற்றப்படுகிறது...", "Report data is unavailable.": "அறிக்கை கிடைக்கவில்லை.", "No member data available yet.": "உறுப்பினர் தரவு இன்னும் இல்லை.",
  "Manage your local administration preferences.": "நிர்வாக விருப்பங்களை நிர்வகிக்கவும்.", "Administrator preferences": "நிர்வாகி விருப்பங்கள்", "Display name": "காட்சிப் பெயர்", "Save preferences": "விருப்பங்களைச் சேமி", "Preferences saved in this browser.": "இந்த உலாவியில் விருப்பங்கள் சேமிக்கப்பட்டன.", "Unable to save preferences in this browser.": "விருப்பங்களைச் சேமிக்க முடியவில்லை.", "Backend connection": "சேவையக இணைப்பு", "API endpoint": "API முகவரி", "This connection is configured for the application deployment.": "செயலிக்கான இணைப்பு அமைக்கப்பட்டுள்ளது.", "Language": "மொழி", "Welcome back": "மீண்டும் வரவேற்கிறோம்", "Sign in to your Namakkal Matrimony workspace.": "நாமக்கல் மேட்ரிமோனி நிர்வாகத்தில் உள்நுழையவும்.", "Email address": "மின்னஞ்சல் முகவரி", "Enter your password": "கடவுச்சொல்லை உள்ளிடவும்", "Show password": "கடவுச்சொல்லைக் காட்டு", "Hide password": "கடவுச்சொல்லை மறை", "Signing in...": "உள்நுழைகிறது...", "Sign in": "உள்நுழை", "Namakkal Matrimony Administration": "நாமக்கல் மேட்ரிமோனி நிர்வாகம்"
};
const normalize = value => String(value || "").replace(/^[^A-Za-z]+/, "").replace(/&/g, "and").replace(/\s+/g, " ").trim().toLowerCase();
const translations = new Map(Object.entries({ ...tamil, ...customerTamil }).map(([key, value]) => [normalize(key), value]));
function translateTamil(text) {
  const direct = translations.get(normalize(text));
  if (direct) return direct;
  const choice = String(text || "").match(/^(.*?)(?:\s*-\s*|\s+)(Yes|No)$/);
  if (choice) return `${translateTamil(choice[1])} - ${translations.get(normalize(choice[2]))}`;
  return text;
}
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("customerLanguage") === "ta" ? "ta" : "en");
  useEffect(() => {
    document.documentElement.lang = language;
    try { localStorage.setItem("customerLanguage", language); } catch {}
  }, [language]);
  return <Context.Provider value={{ language, setLanguage, t: text => language === "ta" ? translateTamil(text) : text }}>{children}</Context.Provider>;
}
export const useLanguage = () => useContext(Context);
export function LanguageSelect() {
  const { language, setLanguage, t } = useLanguage();
  return <select className="language-select" aria-label={t("Language")} value={language} onChange={e => setLanguage(e.target.value)}><option value="en">English</option><option value="ta">தமிழ்</option></select>;
}
